### ISSUE TITLE
Logout button is non-descript

### ISSUE THREAD

**Issue by Rittersm** [marthix/unite#6]
The logout button is a little vague.... I couldn't tell what it was representing and accidentally logged out of my account

**Comment by Rittersm** [comment]
Just noticed the tooltip.... there is quite a delay and users might click logout before the tip pops up

**Comment by mldenne** [comment]
The logout button also looks like something I might click to leave your site and go onto Discord...like it is a gateway to the next step!

**Comment by marthix** [comment]
Switched it over to text instead.
